// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAlH7HmyATUv1pmWXkPNnZs3KlcNEgYc',
    appId: '1:641970037966:web:3b2548c3f609834d1f5c9f',
    messagingSenderId: '641970037966',
    projectId: 'kazerest-form-e3f51',
    authDomain: 'kazerest-form-e3f51.firebaseapp.com',
    storageBucket: 'kazerest-form-e3f51.firebasestorage.app',
    measurementId: 'G-M0HFGC91VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlDsHjIaC7_LwxX0YfWRnxOYJf1MAD_kU',
    appId: '1:641970037966:android:e7b3eeb7c1ad600b1f5c9f',
    messagingSenderId: '641970037966',
    projectId: 'kazerest-form-e3f51',
    storageBucket: 'kazerest-form-e3f51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrJC5CIh612YMuoDdcyduzmVopzLQgks',
    appId: '1:641970037966:ios:f71b0cc695735b701f5c9f',
    messagingSenderId: '641970037966',
    projectId: 'kazerest-form-e3f51',
    storageBucket: 'kazerest-form-e3f51.firebasestorage.app',
    iosBundleId: 'com.example.kazerestForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGrJC5CIh612YMuoDdcyduzmVopzLQgks',
    appId: '1:641970037966:ios:f71b0cc695735b701f5c9f',
    messagingSenderId: '641970037966',
    projectId: 'kazerest-form-e3f51',
    storageBucket: 'kazerest-form-e3f51.firebasestorage.app',
    iosBundleId: 'com.example.kazerestForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKAlH7HmyATUv1pmWXkPNnZs3KlcNEgYc',
    appId: '1:641970037966:web:01dc3a12e150f9271f5c9f',
    messagingSenderId: '641970037966',
    projectId: 'kazerest-form-e3f51',
    authDomain: 'kazerest-form-e3f51.firebaseapp.com',
    storageBucket: 'kazerest-form-e3f51.firebasestorage.app',
    measurementId: 'G-5ET1YN52YN',
  );

}