// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7eOMuO3Kz2mqaHBDjuV9bBtksb9Qw0w0',
    appId: '1:12733727606:web:ef1a7e8200d0484f437057',
    messagingSenderId: '12733727606',
    projectId: 'kazerest-form',
    authDomain: 'kazerest-form.firebaseapp.com',
    storageBucket: 'kazerest-form.firebasestorage.app',
    measurementId: 'G-HYFEN7C7HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuDl_96ntEl1-SZMB5YoKkW2wrigakdI',
    appId: '1:12733727606:android:f41f34863679bd6a437057',
    messagingSenderId: '12733727606',
    projectId: 'kazerest-form',
    storageBucket: 'kazerest-form.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRhQEppCZChYxUdGkU1M-dVjG-m1PMSMo',
    appId: '1:12733727606:ios:cb54d306ea4af7bc437057',
    messagingSenderId: '12733727606',
    projectId: 'kazerest-form',
    storageBucket: 'kazerest-form.firebasestorage.app',
    iosBundleId: 'com.example.kazerestForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRhQEppCZChYxUdGkU1M-dVjG-m1PMSMo',
    appId: '1:12733727606:ios:cb54d306ea4af7bc437057',
    messagingSenderId: '12733727606',
    projectId: 'kazerest-form',
    storageBucket: 'kazerest-form.firebasestorage.app',
    iosBundleId: 'com.example.kazerestForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7eOMuO3Kz2mqaHBDjuV9bBtksb9Qw0w0',
    appId: '1:12733727606:web:179b9bf7b4e791fa437057',
    messagingSenderId: '12733727606',
    projectId: 'kazerest-form',
    authDomain: 'kazerest-form.firebaseapp.com',
    storageBucket: 'kazerest-form.firebasestorage.app',
    measurementId: 'G-HYFEN7C7HT',
  );
}
